server:
  port: 9000 # ??? ??? ???? ??
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR # 500 ??? ???? ???
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException # ??? ??? ??? ??? ???
            backoff: # ???? firstBackoff (factor^n) ??? ??? ??
              firstBackOf: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      httpclient: # http ?????? ?? ?? ??
        connect-timeout: 2000 # ??? ??????? ???? (???)
        response-timeout: 5s # ??? ?? ???? ????(??)
        pool:
          type: elastic # ?? ? ??
          max-idle-time: 15s # ?? ??? ??? ? ???? ??
          max-life-time: 60s # ?? ??? ?? ?? ??
      routes: # ??? ?? ??
        - id: catalog-route # ??? ID
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/books/** # ???? ??? ??? ????.
          filters:
            - name: CircuitBreaker
              - args:
                  name: catalogCircuitBreaker
                  fallbackUrl: forward:/catalog-fallback # ??? ?? ??? ? ??? ? URL? ??
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002} # ?ORDER_SERVICE_URL? ???? ??? : ?? ?? ?? ????? ??
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker # ?? ????? ?? ??? ??? ??
              args:
                name: orderCircuitBreaker
  lifecycle:
    timeout-per-shutdown-phase: 15s # ??? ?? ??? 15?? ??

logging:
  level:
    org.springframework.cloud.gateway: DEBUG