server:
  port: 9000 # ??? ??? ???? ??
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes: # ??? ?? ??
        - id: catalog-route # ??? ID
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/books/** # ???? ??? ??? ????.
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002} # ?ORDER_SERVICE_URL? ???? ??? : ?? ?? ?? ????? ??
          predicates:
            - Path=/orders/**
  lifecycle:
    timeout-per-shutdown-phase: 15s # ??? ?? ??? 15?? ??

logging:
  level:
    org.springframework.cloud.gateway: DEBUG