server:
  port: 9000 # ??? ??? ???? ??
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # ??? ?? ??? 15?? ??
  config:
    import: "optional:configserver:"

  cloud:
    gateway:
      default-filters:
        - SaveSession # ??? ???? ???? ?? ?? ???? ????.
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR # 500 ??? ???? ???
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException # ??? ??? ??? ??? ???
            backoff: # ???? firstBackoff (factor^n) ??? ??? ??
              firstBackOff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10 # ?? ??? ???? ??? ?
              burstCapacity: 20 # ?? 20? ???? ??
              requestedTokens: 1 # ??? ?? ??? ? ?? ??? ????? ??
      httpclient: # http ?????? ?? ?? ??
        connect-timeout: 2000 # ??? ??????? ???? (???)
        response-timeout: 5s # ??? ?? ???? ????(??)
        pool:
          type: elastic # ?? ? ??
          max-idle-time: 15s # ?? ??? ??? ? ???? ??
          max-life-time: 60s # ?? ??? ?? ?? ??
      routes: # ??? ?? ??
        - id: catalog-route # ??? ID
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}
          predicates:
            - Path=/books/** # ???? ??? ??? ????.
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback # ??? ?? ??? ? ??? ? URL? ??
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002} # ?ORDER_SERVICE_URL? ???? ??? : ?? ?? ?? ????? ??
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker # ?? ????? ?? ??? ??? ??
              args:
                name: orderCircuitBreaker

  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s

resilience4j:
  circuitbreaker:
    configs:
      default: # ?? ?? ????? ?? ?? ??
        slidingWindowSize: 20 # ??? ??? ??? ? ??? ??? ????? ???? ???? ??? ??
        permittedNumberOfCallsInHalfOpenStatus: 5 # ??? ??? ??? ? ???? ??? ?
        failureRateThreshold: 50 # ???? ??? ???? ??? ?? ??? ???.
        waitDurationInOpenState: 15000 # ?? ???? ??? ??? ???? ??? ??(???)
  timelimiter:
    configs:
      default: # ?? ?? ??? ?? ?? ??
        timeoutDuration: 5s # ???? ?? (?)

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.gateway: DEBUG